DEFINE_PATCH_FUNCTION CHECK_EXTENSION
STR_VAR
    extension = ""
BEGIN
    PATCH_IF STRING_LENGTH "%extension%" = 0 BEGIN
        PATCH_FAIL "Extension is empty"
    END
    SET last_index = (STRING_LENGTH "%SOURCE_RES%") + 1
    LPF SUBSTRING INT_VAR start = last_index length = 3 STR_VAR string = "%SOURCE_FILE%" RET ex = substring END
    PATCH_IF "%ex%" STRING_COMPARE_CASE "%extension%" != 0 BEGIN
        PATCH_FAIL "This function only works for .%extension% files"
    END
END
