LAF ADD_KIT_EX
    INT_VAR
        help       = RESOLVE_STR_REF(@25000)
        biography  = RESOLVE_STR_REF(@1)
    STR_VAR
        kit_name   = ~ZS_SHADOWDANCER~
        source_kit = ~SHADOWDANCER~
        backstab   = ~1 2 2 2 2 3 3 3 3 4~
        thiefskl   = ~40 15~
        clswpbon   = ~0 0 3~
        clab_path  = ~%MOD_FOLDER%/abilities/ZSSDCLAB.2da~
        luabbr     = ~ZSSD~
    RET kit_id
END
