///// HIDE IN PLAIN SIGHT \\\\\
COPY_EXISTING ~zs#sdl1b.spl~ ~override~
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@9) desc=RESOLVE_STR_REF(@10) END

    PATCH_FOR_EACH skill IN 31 51 76 101 151 201 251 BEGIN
        LPF ALTER_EFFECT INT_VAR parameter2="%zs_hideinshadows_<n%" match_parameter1=%skill% END
    END

    LPF ALTER_EFFECT INT_VAR parameter2="%zs_hideinshadows_>n%" match_parameter1=250 END 

// ensure hide in plain sight complete dispel (mostly just to remove the "invisibility faded" sound at the end) with simple detect invisibility spells
COPY_EXISTING ~sppr309.spl~ ~override~
              ~spwi203.spl~ ~override~
    PATCH_FOR_EACH res IN ~zs#sdl1p~ ~zs#sdl1q~ ~zs#sdl1r~ ~zs#sdl1s~ ~zs#sdl1t~ ~zs#sdl1u~ ~zs#sdl1v~ BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR target=1 opcode=321 STR_VAR resource = ~%res%~ END
    END
IF_EXISTS

COPY_EXISTING ~zs#sdl1m.spl~ ~override~ // Hide in plain sight
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1=RESOLVE_STR_REF(@10010) END