COPY_EXISTING ~zs#sdh02.spl~ ~override~ // One With The Shadow
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@13) desc=RESOLVE_STR_REF(@14) END

COPY_EXISTING ~zs#sdh2d.spl~ ~override~ // critical hit effect One With The Shadow
    LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 139 match_timing = 0 parameter1 = RESOLVE_STR_REF(@23) END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 139 match_timing = 3 parameter1 = RESOLVE_STR_REF(@24) END
