COPY_EXISTING ~spcl936.spl~ ~override~ // Shadow Twin, fixed wrong duration, feedback in log
    LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@60) END // new clarifying description
    LPF ALTER_EFFECT INT_VAR silent = 1 match_duration = 60 duration = 120 END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point=0 opcode=139 target=1 timing=3 parameter1=RESOLVE_STR_REF(@500) duration=120 END
IF_EXISTS

COPY_EXISTING ~simulacr.spl~ ~override~ // fixes issues in 2.6.6 of simulacra's, prevents Summon Shadow, Summon Nighthaunt, and Shadow Twin in abilities
    LPF DELETE_EFFECT INT_VAR match_opcode = 144 END
    LPF ADD_SPL_SELFEFF STR_VAR effects = ~op=172,res=zs#sdl4a;op=172,res=spcl936;op=172,res=zs#sdl4b~ END
BUT_ONLY