COPY_EXISTING ~spcl938.spl~ ~override~ // Shadow Form, adds the extra effects
    LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@11) END
    SET op9_loc_speed = 255 + (20 << 16)
    LPF ADD_SPL_SELFEFF INT_VAR dur=30 p1=50 rd=0 pwr=0 STR_VAR effects = ~op=321,dur=0,ip=0,res=spwish12;op=321,dur=0,ip=0,res=spdwd02;op=321,dur=0,ip=0,res=spcl907;op=321,ip=0,dur=0,res=zs#sdl5a;op=7,p2=255,p1=136;op=291,p2=1,p1=0,ip=3;op=146,p2=1,p1=0,dur=0,res=zs#sfh0;op=146,p1=0,p2=1,dur=0,res=zs#sfh1;op=215,p2=1,dur=1,res=zssevfx1;op=27;op=173;op=28;op=85;op=29;op=30;op=84;op=31;op=69,p1=0;op=204,p1=0,p2=3,ip=4;op=0,p1=4;op=98,p1=1;op=9,p1=1024402944,p2=%op9_loc_speed%;op=51,p1=33752320,p2=255;op=101,p1=0,p2=155;op=101,p1=0,p2=116;op=101,p1=0,p2=70;op=101,p1=0,p2=193;op=101,p1=0,p2=47;op=206,p1=0,res=zssdfb1;op=206,p1=0,res=zssdfb2;op=292,p2=1~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 101 parameter2 = 12 target=1 END
    
    PATCH_IF GAME_IS ~iwdee~ BEGIN
        LPF ALTER_EFFECT INT_VAR match_opcode=61 opcode=50 duration=30 timing=0 parameter1="-784830976" parameter2=op9_loc_speed END
    END ELSE BEGIN
        LPF ALTER_EFFECT INT_VAR match_opcode=50 parameter1="-784830976" parameter2=op9_loc_speed END
    END

    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 30 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=1 match_duration = 30 duration = 36 END
    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 40 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=2 match_duration = 30 duration = 42 END
    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 50 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=3 match_duration = 30 duration = 48 END
IF_EXISTS

COPY_EXISTING ~spwish12.spl~ ~override~
              ~spdwd02.spl~  ~override~ 
              ~spcl907.spl~  ~override~ 
    LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = "spcl907" resource="zs#sdl5a" END
    LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = "spcl907" resource="spcl938" END

DEFINE_PATCH_MACRO patch_file BEGIN
    LPF ALTER_EFF_FILE INT_VAR opcode = 326 parameter2 = 139 parameter1 = 2**22 STR_VAR resource="zsseviv2" END 
END
LAF CREATE_EQ_EFF STR_VAR filename = "zsseviv0" END

DEFINE_PATCH_MACRO patch_file BEGIN
    LPF ADD_SPL_SELFEFF STR_VAR effects=~op=321,res=zsseviv2~ END 
END
LAF CREATE_SELF_SPL STR_VAR filename = "zsseviv1" END

DEFINE_PATCH_MACRO patch_file BEGIN
    LPF ADD_SPL_SELFEFF STR_VAR effects=~op=325,p1=2,dur=30~ END
    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 30 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=1 match_duration = 30 duration = 36 END
    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 40 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=2 match_duration = 30 duration = 42 END
    LPF ADD_SPELL_HEADER INT_VAR copy_header = 1 zs_min_level_for_copy = 50 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header=3 match_duration = 30 duration = 48 END
END
LAF CREATE_SELF_SPL STR_VAR filename = "zsseviv2" END

COPY_EXISTING ~zs#sdl5a.spl~ ~override~ // SHADOW EVADE
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@25) desc=RESOLVE_STR_REF(@26) END
    LPF CLONE_EFFECT INT_VAR match_opcode=20 opcode=146 parameter2=1 STR_VAR resource = "zsseviv2" insert="below" END
    LPF CLONE_EFFECT INT_VAR match_opcode=20 opcode=272 parameter2=3 parameter1=1 STR_VAR resource = "zsseviv0" insert="last" END

COPY_EXISTING ~zs#sdh08.spl~ ~override~ // SHADOW EVADE IMPROVE HLA
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@27) desc=RESOLVE_STR_REF(@28) END