COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/shadow_scripts/zs_sdshd.d~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/shadow_scripts/zs_sdshd.baf~

///// SUMON SHADOW \\\\\
COPY_EXISTING ~zs#sdl4a.spl~ ~override/zs#sdl4c.spl~
COPY_EXISTING ~zs#sdl4a.spl~ ~override~ // Summon Shadow
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@7) desc=RESOLVE_STR_REF(@8) END
    LPF ALTER_EFFECT INT_VAR duration=999999999 timing=1 END
    FOR (i = 4; i <= 28; ++i) BEGIN
        SPRINT filename_end ~%i%~
        PATCH_IF i < 10 BEGIN
            SPRINT filename_end ~0%i%~
        END
        LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource=~zs#sds%filename_end%~ resource=~zs#sdv%filename_end%~ END
    END

DEFINE_PATCH_MACRO apply_spl_code BEGIN
    WRITE_ASCII 0x248 ""
    WRITE_ASCII 0x250 ""
    WRITE_ASCII 0x280 "ZS_SHADOW"
    LPF ALTER_CRE INT_VAR name=shade_name tooltip=shade_name STR_VAR dialog=~zs_sdshd~ END
    ADD_CRE_ITEM "imoenhp1" #1 #0 #0 ~unstealable&undroppable~ ~belt~
    LPF ADD_CRE_EFFECT INT_VAR opcode=17 timing=3 parameter1=100 target=1 parameter2=2 END
    LPF ADD_CRE_EFFECT INT_VAR opcode=112 timing=10 parameter1=3 target=1 duration=20 STR_VAR resource=~imoenhp1~ END
    LPF ADD_CRE_EFFECT INT_VAR opcode=68 timing=3 parameter1=1 target=1 duration=2399 STR_VAR resource = "bdether" END
END

ACTION_IF GAME_IS "iwdee" BEGIN
    COPY_EXISTING ~zsshcomm.itm~ ~override~
                  ~zsshcomn.itm~ ~override~
                  ~zsshcomo.itm~ ~override~
                  ~zsshcomp.itm~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode=267 match_parameter1=32089 parameter1=35571 END
    BUT_ONLY
END

OUTER_SET shade_name = RESOLVE_STR_REF(@250)
COPY_EXISTING ~zs#sds04.cre~ ~override~ // Shadow
              ~zs#sds05.cre~ ~override~
              ~zs#sds06.cre~ ~override~
              ~zs#sds07.cre~ ~override~
              ~zs#sds08.cre~ ~override~
              ~zs#sds09.cre~ ~override~
              ~zs#sds10.cre~ ~override~
              ~zs#sds11.cre~ ~override~
    LPM apply_spl_code
BUT_ONLY

OUTER_SET shade_name = RESOLVE_STR_REF(@251)
COPY_EXISTING ~zs#sds12.cre~ ~override~ // Greater Shadow
              ~zs#sds13.cre~ ~override~
              ~zs#sds14.cre~ ~override~
              ~zs#sds15.cre~ ~override~
              ~zs#sds16.cre~ ~override~
              ~zs#sds17.cre~ ~override~
              ~zs#sds18.cre~ ~override~
              ~zs#sds19.cre~ ~override~
    LPM apply_spl_code
BUT_ONLY

OUTER_SET shade_name = RESOLVE_STR_REF(@252)
COPY_EXISTING ~zs#sds20.cre~ ~override~ // Shadowlord
              ~zs#sds21.cre~ ~override~
              ~zs#sds22.cre~ ~override~
              ~zs#sds23.cre~ ~override~
              ~zs#sds24.cre~ ~override~
              ~zs#sds25.cre~ ~override~
              ~zs#sds26.cre~ ~override~
              ~zs#sds27.cre~ ~override~
    LPM apply_spl_code
BUT_ONLY

OUTER_SET shade_name = RESOLVE_STR_REF(@253)
COPY_EXISTING ~zs#sds28.cre~ ~override~ // Greater shadowlord
    LPM apply_spl_code
BUT_ONLY

OUTER_SET shade_name = RESOLVE_STR_REF(@254)
COPY_EXISTING ~zs#sds36.cre~ ~override~ // Nighthaunt
              ~zs#sds38.cre~ ~override~
              ~zs#sds40.cre~ ~override~
    LPM apply_spl_code
BUT_ONLY

COPY_EXISTING_REGEXP ~^zs#sds[0-9][0-9]\.eff$~ ~override~
    WRITE_ASCII 0x70 ~bdether~ #8
BUT_ONLY

ACTION_IF GAME_IS "bgee" BEGIN

    COPY_EXISTING ~zssdsw8b.spl~ ~override~ // Shadow Weapon
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 25803 END
    COPY_EXISTING ~zssdsw8c.spl~ ~override~ // Shadow Weapon
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 25802 END

END ELSE ACTION_IF GAME_IS "iwdee" BEGIN

    COPY_EXISTING ~zssdsw8b.spl~ ~override~ // Shadow Weapon
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 35497 END

    COPY_EXISTING ~zssdsw8c.spl~ ~override~ // Shadow Weapon
        LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = 35498 END

END

DEFINE_ACTION_MACRO create_helper_cre BEGIN
    // create a new helper creature per shadow tier
    COPY_EXISTING ~cutspy.cre~ ~override/zssinv%filename_end%.cre~
        WRITE_BYTE 0x234 i
        WRITE_ASCII 0x260 ~zssdps%filename_end%~ #8
        LPF DELETE_EFFECT INT_VAR match_opcode = 268 END
        LPF ALTER_EFFECT INT_VAR duration=1 timing=0 END

    // create a new eff summoning to the helper creature based on shadow summoning
    COPY_EXISTING ~zs#sds%filename_end%.eff~ ~override/zs#sdv%filename_end%.eff~
        WRITE_ASCII 0x30 "zssinv%filename_end%" #8
        WRITE_LONG 0x24 1
        WRITE_LONG 0x28 999999999
        WRITE_ASCII 0x70 "NONE" #8
        
END

OUTER_FOR (i = 4; i <= 28; ++i) BEGIN

    OUTER_SPRINT filename_end ~%i%~
    ACTION_IF i < 10 BEGIN
        OUTER_SPRINT filename_end ~0%i%~
    END 
    LAM create_helper_cre
                
END

OUTER_FOR (i = 36; i <= 40; i+=2) BEGIN

    OUTER_SPRINT filename_end ~%i%~
    LAM create_helper_cre
                
END

COMPILE ~%MOD_FOLDER%/shadow_scripts/no_dup~

COPY_EXISTING ~zssdsw1b.spl~ ~override~ // Shadow Weapon
              ~zssdsw2b.spl~ ~override~ 
              ~zssdsw3b.spl~ ~override~ 
              ~zssdsw8d.spl~ ~override~ 
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@255) END

COPY_EXISTING ~zs#sdh20.spl~ ~override~ // Summon Nighthaunt (HLA)
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@700000) desc=RESOLVE_STR_REF(@700001) END

COPY_EXISTING ~zs#sdl6b.spl~ ~override~ // Summon Nighthaunt
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@700000) desc=RESOLVE_STR_REF(@700002) END
    LPF ALTER_EFFECT INT_VAR duration=999999999 timing=1 END
    FOR (i = 36; i <= 40; i+=2) BEGIN
        LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource=~zs#sds%i%~ resource=~zs#sdv%i%~ END
    END
