COPY_EXISTING ~zs#sdsa#.spl~ ~override~ // Shadow Fade
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@198) desc=RESOLVE_STR_REF(@199) END

COPY_EXISTING ~zs#sdsa.spl~ ~override~ // Normal Fade
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@200) desc=RESOLVE_STR_REF(@201) END

COPY_EXISTING ~zs#sdsi.spl~ ~override~ // Fade Improved
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@212) desc=RESOLVE_STR_REF(@213) END

COPY_EXISTING ~zs#sdsb.spl~ ~override~ // Drain Life
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@202) desc=RESOLVE_STR_REF(@203) END

COPY_EXISTING ~zs#sdsd.spl~ ~override~ // Vampiric Touch
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@204) desc=RESOLVE_STR_REF(@205) END

COPY_EXISTING ~zs#sdsf.spl~ ~override~ // Teleport without error
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@206) desc=RESOLVE_STR_REF(@207) END

COPY_EXISTING ~zs#sdsg.spl~ ~override~ // Beshadow Body
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@208) desc=RESOLVE_STR_REF(@209) END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1=RESOLVE_STR_REF(@20209) END

COPY_EXISTING ~zs#sdsj.spl~ ~override~ // Dispel magic shadow
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@214) desc=RESOLVE_STR_REF(@215) END

COPY_EXISTING ~zs#sdsk.spl~ ~override~ // Doom the living
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@216) desc=RESOLVE_STR_REF(@217) END

COPY_EXISTING ~zs#sdsm.spl~ ~override~ // See invisibility
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@218) desc=RESOLVE_STR_REF(@219) END

ADD_PROJECTILE ~%MOD_FOLDER%/projectiles/zssddark.pro~

COPY_EXISTING ~zs#sdsh.spl~ ~override~ // Darkness 15' feet
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@210) desc=RESOLVE_STR_REF(@211) END
    LPF ALTER_HEADER INT_VAR match_type = 1 projectile = %zssddark% END

COPY_EXISTING ~zs#sdsn.spl~ ~override~ // Umbral Swap
    LPF ALTER_SPELL INT_VAR name=RESOLVE_STR_REF(@220) desc=RESOLVE_STR_REF(@221) END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1=RESOLVE_STR_REF(@22200) END